#!/bin/sh
# Read user input, assign stdin to keyboard
exec < /dev/tty
status=$?
while read -p "Do you want to run lint before execution? (Y/n) " yn; do
    case $yn in
        [Yy] ) LIST=$(git diff-index --name-only --diff-filter=d HEAD | grep .*\.[jt]sx\\? | grep -v json); if [ $LIST ]; then eslint $LIST; fi; status=$? && break;;
        [Nn] ) exit 0;;
        * ) echo "Please answer y (yes) or n (no):" && continue;
    esac
done
if [ $status -eq 0 ]
then
  echo "No linting issues found. Executing command!"
  exit 0
else
  while read -p "Linting failed. Do you want to execute nevertheless? (Y/n) " yn; do
      case $yn in
          [Yy] ) exit 0;;
          [Nn] ) exit 1;;
          * ) echo "Please answer y (yes) or n (no):" && continue;
      esac
  done
fi
